### ISSUE TITLE
Osa 2 / Tietokantataulujen lisääminen ja poistaminen: Pieni typo

### ISSUE THREAD

**Issue by jtompuri** [rage/tikape-19#13]
"Tallennettavan tiedon muoto ja tyyppi halutaan määrittää sekä tiedon hakemiseen ja tallentamiseen liittyvän tehokkuuden vuoksi, että **tietokannanhallinnanjärjestelmän** toiminnan vuoksi. Kun **tietokannanhallinnanjärjestelmälle** kerrotaan tallennettavan tiedon **muotoa** ja tyyppi, tietokannanhallintajärjestelmä pystyy varmistamaan, että tallennettava tieto on oikean muotoista."

tietokannanhallinnanjärjestelmän => tietokannanhallintajärjestelmän
tietokannanhallinnanjärjestelmälle => tietokannanhallintajärjestelmälle
muotoa => muoto

**Comment by avihavai** [comment]
Kiitos! Onpas tuo tietokannanhallintajärjestelmä vaikea sana.. :+1:
